services:
    postgres:
        image: pgvector/pgvector:pg16
        container_name: work_asistant_app_db
        ports:
            - "5432:5432"
        dns:
            - 8.8.8.8
            - 8.8.4.4
        environment:
            DB_HOST: postgres
            POSTGRES_DB: ${DB_NAME:-database}
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASS:-postgres}
            POSTGRES_HOST_AUTH_METHOD: trust

        env_file:
          - ./backend/.env
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5


    fastapi-app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: work_asistant_app
        restart: always
        ports:
            - "8000:8000"
        dns:
            - 8.8.8.8
            - 8.8.4.4
        env_file:
            - ./backend/.env
        environment:
            DB_HOST: postgres
            REDIS_HOST: redis-db
        depends_on:
            postgres:
                condition: service_healthy

        networks:
            - app_network

        volumes:
             - ./backend:/app

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: work_asistant_app_frontend
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - ./frontend/.env
        environment:
            - API_URL=http://localhost:8000
            - WS_URL=ws://localhost:8000
        depends_on:
            - fastapi-app
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    postgres_data: